[GLOBAL]
pants_version = "2.12.0"

backend_packages.add = [
  "pants.backend.python",
  "pants.backend.python.typecheck.mypy",
  "pants.backend.python.lint.flake8",
#   "pants.backend.experimental.python.lint.autoflake",
#   "pants.backend.plugin_development",
  "pants.backend.codegen.protobuf.python",
#   "pants.backend.experimental.python",
  "pants.backend.docker",
]

#plugins = []

#pythonpath = ["%(buildroot)s/pants-plugins"]

[source]
root_patterns = [
  "/src/proto",
  "/src/server",
  "/src/client"
]


# [python-repos]
# indexes = ["http://url.to.artifactory.com"]


[anonymous-telemetry]
enabled="False"

[python]
# Python version
interpreter_constraints = ["==3.7.*"]
#requirement_constraints = "3rdparty/constraints.txt"